# Generated by Django 4.1.7 on 2023-05-05 19:46

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Image must be 250px by 250px', null=True, upload_to='avatars/', validators=[users.models.validate_avatar]),
        ),
    ]
