# Generated by Django 4.1.7 on 2023-04-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_review_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
